.github/PULL_REQUEST_TEMPLATE/adapters_template.md, .github/PULL_REQUEST_TEMPLATE/default_template.md, .github/pull_request_template.md, LICENSE.md, README.md, docs/adapters.md
- Add adapters_template.md to .github/PULL_REQUEST_TEMPLATE/ with detailed guidelines for TVL and transaction points calculation.
- Add default_template.md to .github/PULL_REQUEST_TEMPLATE/ for general changes.
- Update pull_request_template.md to provide links to the specific templates.
This helps in standardizing the pull request submissions and ensuring necessary information is provided by contributors.
=> docs(templates): add pull request templates

src/app.service.ts, src/points/adapter.service.ts
layerbank points compensation from 4.10 to 4.25
- \[x\] Bug fix
- \[ \] New feature
- \[ \] Breaking change
- \[ \] Documentation update
=> fix: layerbank points compensation

src/app.service.ts
due to incorrectly awaiting a promise, the points were not processed correctly
=> fix: compensate layerbank points

src/config/projectTokenBooster.ts
=> fix: logx config

src/app.service.ts
=> fix: points at 2051369

src/adapters/novaswap/execution/src/index.ts, src/app.service.ts, src/booster/booster.service.ts, src/points/tvlPoint.service.ts
duplicated key issue on novaswap adapter data
=> fix: novaswap adapter issue

src/app.module.ts
=> fix: rename issue

src/points/txVolPoint.service.ts
=> fix: tv vol issue

src/config/projectTxBooster.ts, src/points/txNumPoint.service.ts, src/points/txVolPoint.service.ts
=> fix: tx booster

src/adapters/rubic/execution/.env.example, src/adapters/rubic/subgraph/.env.example, src/adapters/rubic/subgraph/package.json, src/adapters/rubic/subgraph/src/rubic-multi-proxy.ts
Add env.example for rubic deployment
=> fix: add env.example

src/adapters/agx/execution/src/sdk/lib.ts, src/points/adapter.service.ts, src/repositories/redistributeBalance.repository.ts
=> fix: redistribute point issue

src/config/projectTokenBooster.ts, src/tokens.ts
=> feat: support uniETH on novaswap

src/adapters/wagmi/subgraph/subgraph.yaml
=> fix: pool file name

src/entities/balanceOfLp.entity.ts, src/migrations/1718160892918-CreatePartitionedBalancesOfLp.ts
Set the balanceOfLp table as a partitioned table
=> feat: balanceOfLp partition table

src/entities/redistributeBalance.entity.ts, src/migrations/1718385578027-AlterRedistributeBalanceTable.ts, src/points/redistributeBalance.service.ts, src/points/redistributePoint.service.ts, src/repositories/redistributeBalance.repository.ts
=> fix: redistribute balance table data

src/migrations/1718385578027-AlterRedistributeBalanceTable.ts
=> fix: migration

src/config/projectTokenBooster.ts, src/points/redistributeBalance.service.ts
=> fix: add shoebill config

src/config/projectTxBooster.ts
=> feat: add zkdx tx config

src/adapters/genHourlyData.js, src/entities/transactionDataOfPoints.entity.ts, src/migrations/1719493165693-ChangeQuantityToString.ts, src/points/redistributeBalance.service.ts, src/repositories/txDataOfPoints.repository.ts
=> fix: lrt block number

src/app.service.ts, src/points/tvlPoint.service.ts, src/points/txNumPoint.service.ts, src/points/txVolPoint.service.ts, src/repositories/blockAddressPointOfLp.repository.ts
=> fix: tx point

src/adapters/novaswap/execution/src/index.ts, src/adapters/novaswap/execution/src/sdk/lib.ts
**NOTE**
____
Description:
update novaswap contract address
=> fix: update novaswap contract address

src/points/calTxPoint.service.ts, src/points/genAdapterData.service.ts, src/points/updatePointStatus.service.ts
resolve the promise with empty array
=> fix: resolve with empty array

src/points/tvlPoint.service.ts, src/repositories/blockAddressPointOfLp.repository.ts
=> fix: remove blockNumber in mapKey

src/adapters/novaswap/execution/src/index.ts, src/migrations/1721312834676-UpdateProjectName.ts, src/points/calTxPoint.service.ts, src/points/genAdapterData.service.ts
=> fix: update project name during gen adapter data

src/migrations/1721354490856-UpdateNovaswapTvlProcessingStatus.ts, src/points/updatePointStatus.service.ts
=> fix: missing points due to unstable service

src/migrations/1721395213204-InsertTvlPointDataDuringDownTime.ts, src/points/calTvlPoint.service.ts, src/points/calTxPoint.service.ts
=> fix: avoid deadlock

docs/adapters.md
update adapter docs
- \[x\] Documentation update
=> fix: update docs

src/adapters/skyrangers/execution/.env.example, src/adapters/skyrangers/execution/package-lock.json, src/adapters/skyrangers/execution/package.json, src/adapters/skyrangers/execution/src/index.ts, src/adapters/skyrangers/execution/src/sdk/fetch.ts, src/adapters/skyrangers/execution/src/sdk/lib.ts, src/adapters/skyrangers/execution/src/sdk/types.ts, src/adapters/skyrangers/execution/tsconfig.json, src/config/projectTxBooster.ts
**NOTE**
____
- \[x\] New adapters
Description:
___
Please provide the following information based on the type of points calculation:
1. Dapp Description:
2. User Points Calculation Criteria:
3. Solidity Contract Signature Involved in Transactions:
4. Conditions for User Points Calculation:
5. Quantity Calculation Rule:
=> Added skyrangers project

src/points/updatePointStatus.service.ts
=> fix: initiate tx start block number

src/adapters/novaswap/execution/package-lock.json, src/adapters/novaswap/execution/package.json, src/adapters/novaswap/execution/src/abi/gasVault.json, src/adapters/novaswap/execution/src/index.ts, src/adapters/novaswap/execution/src/sdk/fetch.ts, src/adapters/novaswap/execution/src/sdk/lib.ts, src/adapters/novaswap/execution/src/sdk/types.ts
**NOTE**
____
Add SteerProtocol x NovaSwap Point
Description:
When user deposit to Steer Protocol, then he will earn equal novaSwap Point
=> feat: update NovaSwap x SteerProtocol point

src/adapters/novaswap/execution/src/index.ts, src/adapters/novaswap/execution/src/sdk/lib.ts, src/adapters/novaswap/execution/src/sdk/types.ts
**NOTE**
____
Description:
Fix Steer Protocol GasVault validation
=> fix: steer liquidity

src/app.service.ts, src/migrations/1722837985144-InsertTvlPointDataDuringDownTime.ts, src/points/baseData.service.ts, src/points/genAdapterData.service.ts
=> fix: optimize generated point data

src/points/genAdapterData.service.ts
=> fix: memory optimization

src/app.service.ts
=> fix: enable directPointService

src/points/directPoint.service.ts
=> fix: reject error

src/adapters/zns/execution/src/sdk/lib.ts
=> fix: zns point

src/adapters/zns/execution/src/sdk/lib.ts, src/migrations/1723788890836-UpdateZnsStatus.ts, src/points/calTxPoint.service.ts, src/points/genAdapterData.service.ts, src/points/updatePointStatus.service.ts
Add logs and reset zns point status
=> fix: reset zns point

src/utils/fetchDataFromGraph.ts
=> fix: fetch timeout

docs/adapters.md, src/adapters/desyn/execution/src/sdk/lib.ts
=> fix: desyn point

src/adapters/predx/execution/package-lock.json, src/adapters/predx/execution/package.json, src/adapters/predx/execution/src/index.ts, src/adapters/predx/execution/src/sdk/lib.ts, src/adapters/predx/execution/src/sdk/types.ts, src/adapters/predx/execution/tsconfig.json, src/config/projectTokenBooster.ts
Please select the appropriate template for your pull request:
- [Adapters Template](?template=adapters_template.md)
=> feat: add predx adapter

src/adapters/desyn/execution/src/sdk/lib.ts
=> fix: desyn funding contract address

src/adapters/sumer/subgraph/src/mappings/markets.ts
**NOTE**
____
Description:
accrualBlockNumber reverted, update to try_accrualBlockNumber.
=> fix sumer index error

src/points/genAdapterData.service.ts
due to logx server error, let's pause the logx points
- [\x\] Bug fix
=> fix: pause logx points

src/adapters/sumer/execution/src/sdk/lib.ts
Please select the appropriate template for your pull request:
- [Adapters Template](?template=adapters_template.md)
- [Default Template](?template=default_template.md)
=> fix: NaN issue
